
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh instance --zone=us-west1-b --command='/bin/sh /home/jiochoi7/pull.sh'